spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    hikari:
      schema: news_schema
  jpa:
    generate-ddl: true

server:
  port: 8080
  host: http://localhost